version: '3.8'

services:
  node:
    image: node:lts
    ports:
    - 80:8000
    volumes:
      - ./projects:/usr/src/app
    working_dir: '/usr/src/app'
    command:  bash -c "npm install && npm start"

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=my-secret-pw
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:my-secret-pw@mongo:27017/

